put $GIT_SSH not in CloneDir
 * git does not clone in a non empty directory

diff --git a/check_git b/check_git
--- a/check_git
+++ b/check_git
@@ -50,7 +50,12 @@ if [[ ! -d $REPO_DIR ]]; then
     echo "Could not create a temporary directory for the git repo; exiting"
     exit $STATE_UNKNOWN
 fi
-trap "rm -Rf $REPO_DIR" EXIT
+GIT_SSH=$(tempfile -d ~/.ssh --prefix git. --suffix .ssh -m 700)
+if [[ ! -x $GIT_SSH ]]; then
+    echo "Could not create a temporary git-ssh file; exiting"
+    exit $STATE_UNKNOWN
+fi
+trap "rm -Rf $REPO_DIR; rm -f $GIT_SSH" EXIT
 
 print_usage() {
     echo "Usage: $PROGNAME repo_url [ --keyfile /path/to/id_file ] [ --push ]"
@@ -92,9 +97,8 @@ while test -n "$1"; do
             keyfile=$2
             shift
 
-            echo "ssh -T -o StrictHostKeyChecking=no -i $keyfile \$*" > $REPO_DIR/.git-ssh
-            chmod 0700 $REPO_DIR/.git-ssh
-            export GIT_SSH=$REPO_DIR/.git-ssh
+            echo "ssh -T -o StrictHostKeyChecking=no -i $keyfile \$*" > $GIT_SSH
+            export GIT_SSH
             ;;
         --push)
             push=1
